//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobalEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Files
    {
        public Files()
        {
            this.FIleError = new HashSet<FIleError>();
        }
    
        public System.Guid Id { get; set; }
        public System.Guid ClientId { get; set; }
        public System.Guid ChanelId { get; set; }
        public string Name { get; set; }
        public string FileLocation { get; set; }
        public System.DateTime CreateDate { get; set; }
    
        public virtual TvClients Clients { get; set; }
        public virtual Chanels Chanels { get; set; }
        public virtual ICollection<FIleError> FIleError { get; set; }
    }
}
