//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobalEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Languages
    {
        public Languages()
        {
            this.IsDelete = 0;
            this.Clients = new HashSet<TvClients>();
        }
    
        public System.Guid Id { get; set; }
        public byte IsDelete { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string Title { get; set; }
        public int Code { get; set; }
    
        public virtual ICollection<TvClients> Clients { get; set; }
        public virtual Chanels Chanels { get; set; }
    }
}
