//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobalEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payments
    {
        public Payments()
        {
            this.IsDelete = 0;
        }
    
        public System.Guid Id { get; set; }
        public System.Guid ClientId { get; set; }
        public byte IsDelete { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public System.DateTime PayDate { get; set; }
        public double Paid { get; set; }
        public double Dept { get; set; }
        public string CurrencyId { get; set; }
    
        public virtual TvClients Clients { get; set; }
        public virtual Currencies Currencies { get; set; }
    }
}
