//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobalEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Templates
    {
        public Templates()
        {
            this.IsDelete = 0;
            this.TemplateParams = new HashSet<TemplateParams>();
        }
    
        public System.Guid Id { get; set; }
        public byte IsDelete { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public string Title { get; set; }
        public string Code { get; set; }
        public Nullable<System.Guid> TemplateParamType { get; set; }
    
        public virtual TemplateParamsType TemplateParamsType { get; set; }
        public virtual ICollection<TemplateParams> TemplateParams { get; set; }
    }
}
