//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GlobalEntity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TvManagerModelContainer : DbContext
    {
        public TvManagerModelContainer()
            : base("name=TvManagerModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TvClients> TvClientsSet { get; set; }
        public virtual DbSet<Chanels> ChanelsSet { get; set; }
        public virtual DbSet<Executors> ExecutorsSet { get; set; }
        public virtual DbSet<UserInfo> UserInfoSet { get; set; }
        public virtual DbSet<Templates> TemplatesSet { get; set; }
        public virtual DbSet<TemplateParams> TemplateParamsSet { get; set; }
        public virtual DbSet<ClientChanels> ClientChanelsSet { get; set; }
        public virtual DbSet<ClientState> ClientStateSet { get; set; }
        public virtual DbSet<ChanelState> ChanelStateSet { get; set; }
        public virtual DbSet<Languages> LanguagesSet { get; set; }
        public virtual DbSet<Currencies> CurrenciesSet { get; set; }
        public virtual DbSet<ContactPeople> ContactPeopleSet { get; set; }
        public virtual DbSet<Payments> PaymentsSet { get; set; }
        public virtual DbSet<BanksInfo> BanksInfoSet { get; set; }
        public virtual DbSet<Positions> PositionsSet { get; set; }
        public virtual DbSet<TemplateParamsType> TemplateParamsTypeSet { get; set; }
        public virtual DbSet<Files> FilesSet { get; set; }
        public virtual DbSet<FIleError> FIleErrorSet { get; set; }
    }
}
