//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18449
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConnectService.ServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.ITvManagerServerService")]
    public interface ITvManagerServerService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITvManagerServerService/ClientLogin", ReplyAction="http://tempuri.org/ITvManagerServerService/ClientLoginResponse")]
        bool ClientLogin(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITvManagerServerService/ClientLogin", ReplyAction="http://tempuri.org/ITvManagerServerService/ClientLoginResponse")]
        System.Threading.Tasks.Task<bool> ClientLoginAsync(string login, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITvManagerServerService/LoadClients", ReplyAction="http://tempuri.org/ITvManagerServerService/LoadClientsResponse")]
        GlobalEntity.TvClients[] LoadClients();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITvManagerServerService/LoadClients", ReplyAction="http://tempuri.org/ITvManagerServerService/LoadClientsResponse")]
        System.Threading.Tasks.Task<GlobalEntity.TvClients[]> LoadClientsAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITvManagerServerServiceChannel : ConnectService.ServiceReference.ITvManagerServerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TvManagerServerServiceClient : System.ServiceModel.ClientBase<ConnectService.ServiceReference.ITvManagerServerService>, ConnectService.ServiceReference.ITvManagerServerService {
        
        public TvManagerServerServiceClient() {
        }
        
        public TvManagerServerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TvManagerServerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TvManagerServerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TvManagerServerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool ClientLogin(string login, string password) {
            return base.Channel.ClientLogin(login, password);
        }
        
        public System.Threading.Tasks.Task<bool> ClientLoginAsync(string login, string password) {
            return base.Channel.ClientLoginAsync(login, password);
        }
        
        public GlobalEntity.TvClients[] LoadClients() {
            return base.Channel.LoadClients();
        }
        
        public System.Threading.Tasks.Task<GlobalEntity.TvClients[]> LoadClientsAsync() {
            return base.Channel.LoadClientsAsync();
        }
    }
}
