//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseWorker
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chanels
    {
        public Chanels()
        {
            this.IsDelete = 0;
            this.TimeOffSet = 0;
            this.ClientChanels = new HashSet<ClientChanels>();
            this.Files = new HashSet<Files>();
        }
    
        public System.Guid Id { get; set; }
        public byte IsDelete { get; set; }
        public System.DateTime CreateDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public System.Guid StateId { get; set; }
        public System.Guid LanguageId { get; set; }
        public int TimeOffSet { get; set; }
        public string Title { get; set; }
        public string FileName { get; set; }
    
        public virtual ChanelState ChanelState { get; set; }
        public virtual ICollection<ClientChanels> ClientChanels { get; set; }
        public virtual Languages Languages { get; set; }
        public virtual ICollection<Files> Files { get; set; }
    }
}
