//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseWorker
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clients
    {
        public Clients()
        {
            this.IsDelete = 0;
            this.ClientState = new HashSet<ClientState>();
            this.ClientChanels = new HashSet<ClientChanels>();
            this.Payments = new HashSet<Payments>();
            this.ContactPeople = new HashSet<ContactPeople>();
            this.TemplateParams = new HashSet<TemplateParams>();
            this.Files = new HashSet<Files>();
        }
    
        public System.Guid Id { get; set; }
        public byte IsDelete { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public System.Guid StateId { get; set; }
        public System.Guid ExecutorID { get; set; }
        public string BankInfoId { get; set; }
        public System.Guid LanguageId { get; set; }
        public double PayRate { get; set; }
        public string CurrencyId { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Telephone { get; set; }
        public string Comment { get; set; }
        public System.DateTime RegisterDate { get; set; }
        public Nullable<System.DateTime> BlockedDate { get; set; }
    
        public virtual ICollection<ClientState> ClientState { get; set; }
        public virtual ICollection<ClientChanels> ClientChanels { get; set; }
        public virtual ICollection<Payments> Payments { get; set; }
        public virtual Executors Executors { get; set; }
        public virtual ICollection<ContactPeople> ContactPeople { get; set; }
        public virtual BanksInfo BanksInfo { get; set; }
        public virtual Languages Languages { get; set; }
        public virtual Currencies Currencies { get; set; }
        public virtual ICollection<TemplateParams> TemplateParams { get; set; }
        public virtual ICollection<Files> Files { get; set; }
    }
}
