//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseWorker
{
    using System;
    using System.Collections.Generic;
    
    public partial class Executors
    {
        public System.Guid Id { get; set; }
        public string IsDelete { get; set; }
        public string CreateDate { get; set; }
        public string ModifiedDate { get; set; }
        public string Name { get; set; }
        public string Comment { get; set; }
    
        public virtual Clients Clients { get; set; }
    }
}
